# Explainable Loan Default Risk Scoring System

# Notebook 2: Data Preprocessing

In this notebook, the loan default dataset is preprocessed before training machine learning models.

The preprocessing steps include:

- Loading the dataset
- Inspecting the data
- Removing unnecessary columns
- Encoding categorical variables
- Splitting the dataset into training and testing sets
- Saving the trained label encoders for deployment

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import joblib
import os

# Load the Dataset

The loan default dataset is loaded into a Pandas DataFrame.

In [2]:
df = pd.read_csv("../data/Loan_Default.csv")

df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

# Inspect the Dataset

Understanding the structure of the dataset before preprocessing.

In [3]:
print("Shape of Dataset:", df.shape)

df.info()

Shape of Dataset: (255347, 18)
<class 'pandas.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  str
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  str
 11  EmploymentType  255347 non-null  str
 12  MaritalStatus   255347 non-null  str
 13  HasMortgage     255347 non-null  str
 14  HasDependents   255347 non-null  str
 15  LoanPurpose     255347 non-null  str
 16  HasCoSigner     255347 non-null  str
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), str(8)
memory usage: 46.9 MB

In [4]:
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

# Remove Unnecessary Columns

The LoanID column is only an identifier and does not contribute to prediction.

Therefore, it is removed before model training.

In [5]:
df.drop("LoanID", axis=1, inplace=True)

df.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

# Encode Categorical Features

Machine learning algorithms require numerical input.

Each categorical feature is encoded using a separate LabelEncoder.

The trained encoders are stored for later use during deployment to ensure consistent preprocessing.

In [6]:
label_encoders = {}

categorical_columns = df.select_dtypes(include=["object", "string"]).columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
       'HasDependents', 'LoanPurpose', 'HasCoSigner'],
      dtype='str')

In [7]:
for col in categorical_columns:

    encoder = LabelEncoder()

    df[col] = encoder.fit_transform(df[col])

    label_encoders[col] = encoder

df.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56,85994,50587,520,80,4,15.23,36,0.44,0,0,0,1,1,4,1,0
1,69,50432,124440,458,15,1,4.81,60,0.68,2,0,1,0,0,4,1,0
2,46,84208,129188,451,26,3,21.17,24,0.31,2,3,0,1,1,0,0,1
3,32,31713,44799,743,0,3,7.07,24,0.23,1,0,1,0,0,1,0,0
4,60,20437,9139,633,8,4,6.51,48,0.73,0,3,0,0,1,0,0,0

# Verify Encoded Dataset

The categorical columns have now been converted into numerical values suitable for machine learning.

In [8]:
df.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56,85994,50587,520,80,4,15.23,36,0.44,0,0,0,1,1,4,1,0
1,69,50432,124440,458,15,1,4.81,60,0.68,2,0,1,0,0,4,1,0
2,46,84208,129188,451,26,3,21.17,24,0.31,2,3,0,1,1,0,0,1
3,32,31713,44799,743,0,3,7.07,24,0.23,1,0,1,0,0,1,0,0
4,60,20437,9139,633,8,4,6.51,48,0.73,0,3,0,0,1,0,0,0

# Split Features and Target

The dataset is divided into:

- Features (X)
- Target Variable (y)

In [9]:
X = df.drop("Default", axis=1)

y = df["Default"]

print("Feature Shape :", X.shape)
print("Target Shape  :", y.shape)

Feature Shape : (255347, 16)
Target Shape  : (255347,)

# Train-Test Split

The dataset is divided into training and testing sets.

- 80% Training Data
- 20% Testing Data

Stratified sampling is used to preserve the class distribution.

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Shape :", X_train.shape)
print("Testing Shape  :", X_test.shape)

Training Shape : (204277, 16)
Testing Shape  : (51070, 16)

# Save Label Encoders

The trained LabelEncoders are saved for deployment.

This ensures that the Streamlit application uses the exact same categorical encoding that was used during model training.

In [11]:
os.makedirs("../models", exist_ok=True)

joblib.dump(label_encoders, "../models/label_encoders.pkl")

print("Label encoders saved successfully!")

Label encoders saved successfully!

# Save Feature Names

The feature names are saved so that the deployment application and SHAP explanations use the correct feature order.

In [12]:
joblib.dump(list(X.columns), "../models/feature_names.pkl")

print("Feature names saved successfully!")

Feature names saved successfully!

# Verify Saved Files

The saved preprocessing artifacts are loaded to ensure they were stored successfully.

In [13]:
encoders = joblib.load("../models/label_encoders.pkl")

print("Saved Encoders:")
print(encoders.keys())

Saved Encoders:
dict_keys(['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner'])

In [14]:
feature_names = joblib.load("../models/feature_names.pkl")

print(feature_names)

['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

# Conclusion

The dataset has been successfully preprocessed for machine learning.

The preprocessing pipeline included:

- Removing unnecessary columns
- Encoding categorical variables
- Splitting the dataset into training and testing sets
- Saving LabelEncoders for deployment
- Saving feature names for consistent model inference

The processed data is now ready for model training in the next notebook.